# This file should contain all the record creation needed to seed the database
# with its default values. The data can then be loaded with the
# rails db:seed command (or created alongside the database with db:setup).

csv_records = <<EOCSV
name,description,cause_area,research_policy_and_advocacy,service_delivery,Secondary cause area,Effective Giving of $100,Ein,Website
Against Malaria Foundation,"AMF works to prevent the spread of malaria by distributing long-lasting, insecticide-treated mosquito nets to susceptible populations in developing countries. One AMF bednet costs $2.50 and protects two people from malaria for up to three years. For every ~1500 bednets, a life is saved",global_health,FALSE,TRUE,,"Provide 40 bednets, protecting 60 people from malaria for 3 years",,
Development Media International,"DMI runs television and radio campaigns in developing regions to raise awareness for important health and wellness issues. The focus areas of DMI’s educational media for vulnerable communities are nutrition, hygiene and sanitation, malaria prevention, HIV/AIDS, family planning, and child marriage. DMI works with local broadcasters to create informative and engaging programming, reaching wide communities via large-scale media campaigns ",global_health,TRUE,FALSE,clean_water_and_sanitation,Save the life of someone who would otherwise have died from preventable diseases,,
Evidence Action (a),"Dispensers for Safe Water is a sustainable rural water service that maintains chlorine dispensers directly at the water source, ensuring access to safe drinking water for more than 3 million people in rural Kenya, Uganda, and Malawi. Evidence Action Beta tests and develops new, rigorously evaluated interventions to determine whether they are suitable for scaling. ",clean_water_and_sanitation,TRUE,FALSE,,Provide safe water to 119 community members for one year,,
Deworm the world (Evidence action),"Deworm the World Initiative supports national school-based deworming programs that treat more than 160 million children for parasitic worm infections annually in India, Kenya, Vietnam, and Ethiopia.",global_health,TRUE,FALSE,,Deworm 1000 children,,
Fistula Foundation,"Fistula Foundation trains surgeons and funds operations to repair obstetric fistula, a devastating injury caused by difficult childbirth that renders the woman incontinent. Obstetric fistula affects the poorest women in the poorest parts of the developing world. More than 75 percent of women who suffer from fistula have endured labor that lasted three days or longer, usually with loss of the baby. Fistula can only be cured with surgery, and without proper treatment, women often find it difficult to reintegrate into their communities, including facing ostracism by their families.",women_and_reproductive_rights,FALSE,TRUE,,Cover 10% of the entire surgery and recovery costs of an operation to treat obstetric fistula,,
GiveDirectly,"GiveDirectly provides unconditional cash transfers using cell phone technology to some of the poorest people in Kenya and Uganda. These direct cash transfers allow families to buy much-needed food and shelter, educate their children, and start small businesses.",economic_development,FALSE,TRUE,poverty_alleviation,,,
Global Alliance for Improved Nutrition,"Iodine deficiency is the leading preventable cause of intellectual and development disabilities in the world. Iodine is a vital micronutrient for mental and physical health, yet in many parts of the world, people do not have enough iodine in their normal diet. There is a simple, cost-effective solution: fortifying household salt with iodine. GAIN works with governments and producers to make this happen, helping to make millions of people healthier, smarter, and more productive. It takes an investment of just 15 to 50 cents for GAIN to help provide one additional person with access to adequately iodized salt through their lifetime.",hunger_and_nutrition,FALSE,TRUE,,Lifetime protection against iodine difficiency for 200 people,,
Innovations for Poverty Action,"Innovations for Poverty Action (IPA) is a research group with a scientific approach to discovering and promoting effective solutions to global poverty problems. IPA investigates interventions spanning agriculture, education, health, finance, governance, social protection and post-conflict recovery. The organization works with governments, businesses and NGOs to develop and incubate promising anti-poverty interventions, analyze results, and publicize recommendations. IPA works with partner organizations to evaluate poverty relief interventions using randomized controlled trials to find the most effective ways to have meaningful and lasting impact.",poverty_alleviation,TRUE,FALSE,,,,
Iodine Global Network,"More than 3.5 billion people today are malnourished--that’s roughly than half the world’s population. Iodine deficiency is the leading preventable cause of intellectual and developmental disabilities in the world. The IGN supports and catalyzes national and international iodine nutrition programs, working with public, private, community, and scientific partners. The IGN focuses on universal salt iodization programs throughout the developing world to combat the debilitating cognitive and physical health problems caused by iodine deficiency. ",hunger_and_nutrition,FALSE,TRUE,,Provide 10000 individuals with a year of support sustaining existing protection against iodine deficiency ,,
Living Goods,"Living Goods employs and trains local people--the majority of whom are women--to sell goods and life-saving medical supplies at competitive prices. Living Goods provides businesswomen and saleswomen with employment and entrepreneurial skills while improving health outcomes in their communities. Using a micro-franchise model for direct economic empowerment, women sell their goods door-to-door. These women own and operate their own micro-franchises, while distributing invaluable health and medical supplies to their own communities at affordable prices. The Livings Goods model reduced under-5 mortality by 27 percent and infant (under-1) mortality by 33 percent",economic_development,FALSE,TRUE,global_health,Serve 48 Ugandans through a Community Health Promoter providing families with vital health products and services.,,
One Acre Fund,One Acre Fund is a nonprofit organization that supplies smallholder farmers in East Africa with asset-based financing and agriculture training services to reduce hunger and poverty.,economic_development,FALSE,TRUE,poverty_alleviation,Provide 3 families of 6 with the tools to increase production and profits from supported activities by an average of 50% ($135) in a single season.,,
Oxfam,"Oxfam works to sustainably improve lives through advocacy, disaster relief, education, health, sanitation and women's rights. Oxfam’s work focuses on long-term development programs, emergency assistance, and political advocacy. Within these categories, Oxfam addresses a wide range of issues including agriculture, education, health, HIV/AIDS, climate change, aid effectiveness, emergency response, gender justice, indigenous and minority rights, natural resources, peace and security, private sector, trade and youth outreach. Oxfam works in over 90 countries across the world, with thousands of local partner organizations. Oxfam has been providing emergency relief to the developing world since 1951. It has undertaken thousands of interventions, and at any given time is responding to over 30 emergency situations worldwide.",global_health,FALSE,TRUE,,Provide school meal programs to 2 children for one year.,,
Population Services International,"Women in the developing world who want contraception, but can’t access it, face dire consequences. They run high risks of complications during pregnancy, even death. They struggle to financially care for their families. They drop out of school and don’t continue their education. For over 50 years, they have been committed to using measurement and evaluation to identify and develop the most impactful, innovative and cost-effective solutions to some of the most challenging health issues in global development. PSI's primary focus is on modern family planning and contraception, but they also work in the areas of HIV, malaria, water, sanitation and hygiene, and non-communicable diseases (including diabetes, hypertension and cervical cancer).",women_and_reproductive_rights,FALSE,TRUE,,"Provide 5 years of healthy life to women, children and families in the developing world through disease prevention, maternal health, family planning and other health services.",,
Possible,"Possible delivers high-quality, durable healthcare to the poorest of the poor in rural Nepal. Possible is a pioneer in durable health care, which combines the best of private, public, and philanthropic models. Possible provides free and cost-effective health care services to Nepal’s rural poor in partnership with government medical programs. In doing so, Possible is helping to rebuild health care infrastructure in a country devastated by civil war and natural disasters.",global_health,FALSE,TRUE,,Provide 2 patients with high-quality healthcare in rural Nepal.,,
Project Healthy Children,"Project Healthy Children (PHC) works with national governments and manufacturers to fortify staple foods with essential micronutrients such as iron, folic acid and iodine, protecting populations from debilitating conditions caused by malnutrition. PHC sees that essential micronutrients reach even the most vulnerable populations, an an average cost of 25 cents per person per year. All families are created equal, but not all families are treated equally! 5 million children die every year from malnutrition. That is more than 13,000 deaths a day. With basic nutritional support – vitamins and minerals – these deaths are 100% preventable",hunger_and_nutrition,FALSE,TRUE,,Provide 384 people with food-based micronutrient fortification for one year.,,
Schistosomiasis Control Initiative,"SCI facilitates school-based distributions of deworming tablets, protecting children from debilitating diseases and improving school attendance for less than $0.75 per child.",global_health,FALSE,TRUE,,"Protect 136 children from schistosomiasis for one year, preventing life-threatening conditions including bladder cancer, kidney malfunction, spleen damage, and anaemia.",,
Seva,"Seva's eye care programs serve nearly one million children and adults in 20 countries yearly, including $50 vision-restoring cataract surgeries.",global_health,FALSE,TRUE,,Restore eyesight for 2 people with curable blindness who cannot afford surgery.,,
Village Enterprise,Village Enterprise empowers the ultra poor in rural Africa to lift themselves out of poverty through small sustainable businesses and savings groups.,poverty_alleviation,FALSE,TRUE,,,,
Alliance for Safety and Justice,"""The Alliance for Safety and Justice (ASJ) is a national organization seeking to reduce overreliance on incarceration in states across the U.S. and to promote new safety priorities rooted in community health and well-being""",criminal_justice,FALSE,TRUE,,,,
Fair and Just Prosecution,"The Fair and Just Prosecution project will provide guidance, assistance and networked support to recently elected prosecutors committed to change and innovation as they seek to implement criminal justice system policy and practice reforms in their offices.",criminal_justice,FALSE,TRUE,,,,
The Center for Popular Democracy,"The Center for Popular Democracy encourages more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve, and specifically in the selection of regional Federal Reserve Bank presidents and leaders. ",us_tax_policy,FALSE,TRUE,,,,https://www.cbpp.org
Robin Hood Foundation,"Robin Hood is New York's largest poverty-fighting organization, and since 1988 has focused on finding, funding, and creating programs and schools that generate meaningful and measurable results for families in New York's poorest neighborhoods. Since its founding, Robin Hood has raised more than $2 billion in dollars, goods and services to provide hundreds of the most effective soup kitchens, homeless shelters, schools, job-training programs and other vital services that give New York's neediest citizens the tools they need to build better lives. Robin Hood's board of directors pays all administrative, fundraising and evaluation costs, so 100% of your donation goes directly to organizations helping New Yorkers in need.",poverty_alleviation,FALSE,TRUE,,,,
Tipping Point Community,Tipping Point Community screens non-profits rigorously to find and fund the most effective groups connecting Bay Area individuals and families to the services and opportunities needed to break the cycle of poverty and achieve economic self-sufficiency.,poverty_alleviation,FALSE,TRUE,,,,
Center for Internet Security,"The Center for Internet Security, Inc. (CIS) is a 501c3 nonprofit organization focused on enhancing the cyber security readiness and response of public and private sector entities, with a commitment to excellence through collaboration. CIS provides resources that help partners achieve security goals through expert guidance and cost-effective solutions.",ai_and_cyber_security,FALSE,TRUE,,,,https://cybersecurityventures.com/cybersecurity-associations/
Open Web Application Security Project,"The Open Web Application Security Project (OWASP) is a 501(c)(3) worldwide not-for-profit charitable organization focused on improving the security of software. Our mission is to make software security visible, so that individuals and organizations worldwide can make informed decisions about true software security risks.",ai_and_cyber_security,FALSE,TRUE,,,,https://cybersecurityventures.com/cybersecurity-associations/
Center for Reproductive Rights,"The Center for Reproductive Rights, founded over 20 years ago, is dedicated to protecting women's right to choose in the legal realm. ""We are the only global legal advocacy organization dedicated to reproductive rights, with expertise in both U.S. constitutional and international human rights law,"" states CRR's official website. ""Our groundbreaking cases before national courts, United Nations committees, and regional human rights bodies have expanded access to reproductive healthcare, including birth control, safe abortion, prenatal and obstetric care, and unbiased information.""",women_and_reproductive_rights,FALSE,TRUE,,,,https://www.bustle.com/articles/197444-7-reproductive-rights-organizations-to-donate-to-on-giving-tuesday
National Abortion Federation,"According to NAF's website, ""NAF is the professional association of abortion providers in North America. We are unique among pro-choice organizations because we represent the providers who make reproductive choice a reality."" Some of the services they offer include: ""Providing resources for women seeking abortion care; initiating groundbreaking educational programs for health care professionals; protecting providers and patients from anti-abortion violence; and developing a pivotal, pro-choice advocacy role to represent the voices of abortion providers and women who have chosen this care.""",women_and_reproductive_rights,FALSE,TRUE,,,,https://www.bustle.com/articles/197444-7-reproductive-rights-organizations-to-donate-to-on-giving-tuesday
Sierra Club Foundation,The Sierra Club Foundation promotes efforts to educate and empower people to protect and improve the natural and human environment.,climate_and_environment,TRUE,FALSE,,,,charity navigator
Rainforest Trust,Rainforest Trust helps to purchase and protect threatened rainforests and save endangered wildlife through community engagement and local partnerships.,climate_and_environment,FALSE,TRUE,,,,charity navigator
Trust for Public Land,"The Trust for Public Land conserves land for people to enjoy as parks, gardens, and natural places, ensuring livable communities for generations to come.",climate_and_environment,FALSE,TRUE,,,,charity navigator
Resources for the Future Inc,RFF's primary purpose is to improve environmental and natural resource policy making worldwide through social science research of the highest caliber.,climate_and_environment,TRUE,FALSE,,,,charity navigator
Environmental Defense Fund,Environmental Defense Fund's mission is to preserve the natural systems on which all life depends. What distinguishes EDF from others is the combination of what we protect and how we protect it.,climate_and_environment,FALSE,TRUE,,,,charity navigator
Mercy for Animals,Mercy For Animals primarily works on undercover investigations and online outreach. We find them to be an exceptionally strong organization because of their demonstrated openness to and success in maximizing effectiveness.,animal_suffering,FALSE,TRUE,,,,based on animal charity evaluators' top picks
The Humane League,"The Humane League runs a variety of programs that advocate for farmed animals, including online veg advertising, corporate outreach, and leafleting programs. They continually seek to optimize the impact of their activities.",animal_suffering,FALSE,TRUE,,,,based on animal charity evaluators' top picks
The Good Food Institute,"The Good Food Institute works in an underutilized but critically important area by promoting and developing competitive alternatives to animal-based meat, dairy, and eggs. They provide support in a variety of ways to cellular agriculture and cultured meat companies, including building relationships with distributors and retailers and driving R&D of the products.",animal_suffering,TRUE,FALSE,,,,based on animal charity evaluators' top picks
United Palestinan Appeal,"United Palestinian Appeal, Inc., works to alleviate the suffering of Palestinians, particularly those in the West Bank, Gaza Strip and refugee camps throughout the Middle East, and to contribute to the long-term socioeconomic and cultural development of Palestinian society.",refugees_and_immigration,FALSE,TRUE,,,,charity navigator
Assylum Access,"Globally, we challenge barriers that keep refugees from rebuilding their lives. We do this through personalized legal assistance and by helping refugee communities organize to assert their human rights. We also challenge governments and the UN to develop and promote lasting solutions, shifting the focus from emergency aid to approaches that restore power and agency to refugee men and women.",refugees_and_immigration,FALSE,TRUE,,,,charity navigator
International Rescue Committee,"The International Rescue Committee (IRC) responds to the world's worst humanitarian crises, helping to restore health, safety, education, economic well being, and power to people devastated by conflict and disaster. Founded in 1933 at the call of Albert Einstein, the IRC is at work in over 40 countries and 26 U.S. cities helping people to survive, reclaim control of their future and strengthen their communities.",refugees_and_immigration,FALSE,TRUE,,,,charity navigator
American Refugee Committee,"For over 35 years, ARC has worked with refugees across the globe, in areas like water and sanitation infrastructure, shelter, primary and reproductive health, livelihood support, education, social enterprise and more. We work with people who are suffering through the most difficult times in their lives, reaching over 3 million people each year with lifesaving services. Our work takes place in Rwanda, the Democratic Republic of Congo, South Sudan, Sudan, Uganda, Somalia, Pakistan, Thailand, Myanmar, Jordan, and Syria, with emergency interventions deployed when appropriate. Our programs are as diverse as the people we serve, but they all work together for the same goal: to help people take back control of their lives.",refugees_and_immigration,FALSE,TRUE,,,,charity navigator
Creative Capital,"Creative Capital is a national nonprofit organization that provides integrated financial and advisory support to artists pursuing adventurous projects in all disciplines. Our pioneering approach combines funding, counsel and career development services to enable a project’s success and foster sustainable practices for its grantees.",arts_and_community,FALSE,TRUE,,,,https://www.myphilanthropedia.org/top-nonprofits/national/arts-culture/2010
National Endowment for the Arts,"The National Endowment for the Arts is a public agency dedicated to supporting excellence in the arts, both new and established; bringing the arts to all Americans; and providing leadership in arts education. Established by Congress in 1965 as an independent agency of the federal government, the Endowment is the nation's largest annual funder of the arts, bringing great art to all 50 states, including rural areas, inner cities, and military bases.",arts_and_community,FALSE,TRUE,,,,https://www.myphilanthropedia.org/top-nonprofits/national/arts-culture/2010
Americans for the Arts,"The mission of Americans for the Arts is to serve, advance, and lead the network of organizations and individuals who cultivate, promote, sustain, and support the arts in America.",arts_and_community,FALSE,TRUE,,,,https://www.myphilanthropedia.org/top-nonprofits/national/arts-culture/2010
Massachusetts Association of Community Development Corporations,"The Massachusetts Association of Community Development Corporations (MACDC) is an association of mission-driven community development organizations dedicated to working together and with others to create places of opportunity where people of diverse incomes and backgrounds access housing that is affordable, benefit from economic opportunities and fully participate in the civic life of their community. We achieve this by building and sustaining a high performing and adaptive community development sector that is supported by private and public investment and sound public policies. MACDC, an IRS designated 501(c)(3) nonprofit, is a recipient of Community Investment Tax Credits, which provide a 50% refundable state tax credit to donations of $1,000 or greater.",economic_development,FALSE,TRUE,,,,https://macdc.org/mission-vision-values
Human rights campaign,"Through research, educational efforts and outreach, the Human Rights Campaign (HRC) Foundation encourages gay, lesbian, bisexual and transgender Americans to live their lives openly and seeks to change the hearts and minds of Americans to the side of equality. Programs funded in part or in full through the HRC Foundation include: The HRC Coming Out Project, which encourages GLBT and straight-supportive Americans to come out and live openly; The HRC Family Project, which empowers members of the GLBT community to take action to protect their families; The HRC Historically Black Colleges and Universities Outreach Program, which trains student activists to sustain dialogue, build viable student-led GLBT organizations; The HRC Religion and Faith Program, The HRC Research Center, and The HRC Workplace Project.",human_rights,TRUE,FALSE,,,,
Southern Poverty Law Center,"The Southern Poverty Law Center (SPLC) was founded in 1971 as a small civil rights law firm. Today, SPLC is internationally known for its tolerance education programs, its legal victories against white supremacists and its tracking of hate groups. Throughout its history, SPLC has worked to make the nation's Constitutional ideals a reality. The SPLC legal department fights all forms of discrimination and works to protect society's most vulnerable members, handling innovative cases that few lawyers are willing to take. The SPLC Intelligence Project monitors hate groups and tracks extremist activity throughout the U.S. To combat the causes of hate, SPLC in 1991 established Teaching Tolerance, an educational program to help K-12 teachers foster respect and understanding in the classroom.",human_rights,FALSE,TRUE,,,,
Homes for our troops,"HFOT builds and donates specially adapted custom homes nationwide for severely injured post-9/11 Veterans, to enable them to rebuild their lives.",veterans_affairs,FALSE,TRUE,,A completed home costs $200-500k,,
EOCSV

require 'csv'

csv = CSV.parse(csv_records, :headers => true)

csv.each do |row|
  puts row['name']
  Organization
    .find_or_create_by(ein: row['name'].parameterize)
    .update(
      name: row['name'],
      description: row['description'],
      long_term_impact: row['research_policy_and_advocacy'],
      immediate_impact: row['service_delivery'],
      cause_area: row['cause_area']
    )
end
