class AddUsesOneForTheWorldCheckoutToPartners < ActiveRecord::Migration[7.0]
  def change
    add_column :partners, :uses_one_for_the_world_checkout, :boolean, default: false, null: false

    # For rolling back, I stored the previous values at https://gist.github.com/david-mears-2/db93ad0656bcfb5c628790863501741c
    Partner.where(name: ['One For The World', 'One For The World UK', 'One For The World Canada',
    'One For The World Australia']).update_all(
      uses_one_for_the_world_checkout: true,
      donor_questions_schema: { questions: [{ 'name' => 'phone_number',
      'type' => 'text',
      'title' => 'Mobile phone',
      'options' => [],
      'required' => true },
    { 'name' => 'comms_email',
      'type' => 'checkbox',
      'title' => 'Yes, sign me up for email updates',
      'options' => [],
      'required' => false },
    { 'name' => 'comms_phone',
      'type' => 'checkbox',
      'title' => 'Yes, sign me up for SMS updates',
      'options' => [],
      'required' => false },
    { 'name' => 'birthday',
      'type' => 'date',
      'title' => 'When is your birthday?',
      'options' => [],
      'required' => false },
    { 'name' => 'chapter',
      'type' => 'select',
      'title' => 'Enter your chapter name',
      'options' => ['Accenture',
                    'Australian National University',
                    'Bain',
                    'Bridgewater',
                    'Boston Consulting Group',
                    'Brock University',
                    'Chicago Booth School of Business',
                    'Cardozo Law School',
                    'Columbia University',
                    'Durham University',
                    'George Washington University',
                    'Google',
                    'Kansas University Medical Center',
                    'London School of Economics',
                    'McGill University',
                    'McKinsey',
                    'Meta',
                    'Microsoft',
                    'Northeastern University',
                    'Ohio State University',
                    'Princeton University',
                    'Queens University',
                    'Syracuse University',
                    'Tuck School of Business at Darthmouth',
                    'UNC Kenan-Flagler',
                    'University of Calgary',
                    'University of Cambridge',
                    'University of Cinncinati',
                    'University of Maryland',
                    'University of Miami',
                    'University of Michigan',
                    'University of Nebraska Medical Center',
                    'University of Pennsylvania',
                    'University of Pennsylvania Wharton',
                    'University of Saskatchewan',
                    'University of St Andrews',
                    'University of Virginia Darden School of Business',
                    'University of Virginia Law School',
                    'Vanderbilt University',
                    'Virginia Commonwealth University',
                    'Western University',
                    'Yale School of Management'],
      'required' => true },
    { 'name' => 'givewell_familiar',
      'type' => 'select',
      'title' => "Were you familiar with GiveWell's recommended nonprofits before you encountered One for the World?",
      'options' => %w[Yes No],
      'required' => true },
    { 'name' => 'nonprofit_comms',
      'type' => 'checkbox',
      'title' => 'Share my name, contact info, and donation info with <b>the nonprofits I support</b>, so that they can email me and track their donations better',
      'options' => [],
      'required' => false },
    { 'name' => 'givewell_comms',
      'type' => 'checkbox',
      'title' =>
    'Share my name, contact info, and donation info with <b>GiveWell</b> so that they can email me and track their donations better',
      'options' => [],
      'required' => false },
    { 'name' => 'OFTW_discretion',
      'type' => 'checkbox',
      'title' =>
    'Just like other regranting nonprofits, One for the World has final say on donation allocation. We follow member preferences and will inform you before redirecting donations, if our recommended nonprofits change.',
      'options' => [],
      'required' => true }]}
    )
  end
end
